apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: mtls.tanzu.vmware.com
spec:
  description: >-
    mTLS ensure data protection (security, encryption, compliance) to in-flight
    traffic within a cluster as part of space.
  carvelPackages:
  - refName: mtls.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
      prereleases: {}
    values:
      inline:
        mtlsEnabled: false  #! true/false => STRICT/PERMISSIVE. Default false.
