apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: all-regions.tanzu.vmware.com
spec:
  affinity:
    clusterAffinity:
      clusterSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: Exists
