---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: workload-installer.tanzu.vmware.com
spec:
  description: >-
    Workload installer define the specific characteristics and requirements of
    applications or services running on the cluster.
  carvelPackages:
  - refName: workload-installer.tanzu.vmware.com
    alias: installer
    versionSelection:
      constraints: ">0.0.0"
    excludedKeys:
    - imagePullSecrets
    values:
      inline:
        imagePullSecrets: []
        serviceAccountName: workload-installer
  - refName: workload-imagepull-secret.tanzu.vmware.com
    alias: imagepull-secret
    versionSelection:
      constraints: ">0.0.0"
    values:
      inline:
        #! name of ImagePullSecret to be associated with workload
        #! serviceAccount.
        secretName: workload-imagepull-secret
        #! Service account used for running the workload.
        serviceAccountName: default
